import { useState } from 'react';
import { useForm, ValidationError } from '@formspree/react';
import { Turnstile } from '@marsidev/react-turnstile';
import { Check, Send, MapPin, Phone, Mail } from 'lucide-react';
import { SectionLabel } from '../../shared/SectionLabel';

export function AboutContact() {
  const [state, handleSubmit] = useForm('xgaeeoov');
  const [turnstileToken, setTurnstileToken] = useState('');
  return <section className="section-pad about-contact"><div className="about-block"><SectionLabel>CONTACT US</SectionLabel><h2>Get in <em>touch.</em></h2><div className="contact-locations"><div className="contact-location"><h3>Sri Lanka</h3><p><strong>Segurara Technologies (Pvt) Ltd</strong></p><p><MapPin size={14} /> 42 Lotus Arcade, Ward Place, Colombo 07, Sri Lanka</p><p><Phone size={14} /> +94 11 245 7812</p></div><div className="contact-location"><h3>USA</h3><p><strong>Segurara Technologies LLC</strong></p><p><MapPin size={14} /> 425 Market Street, Suite 310, San Francisco, CA 94105, USA</p><p><Phone size={14} /> +1 415 555 2101</p></div><p className="contact-email"><Mail size={16} /><span>Email <strong>info@segurara.com</strong></span></p></div></div><div className="contact-card" id="contact"><div><SectionLabel>GET IN TOUCH</SectionLabel><h2>Let's build better <em>security context.</em></h2></div>{state.succeeded ? (<div className="contact-success"><Check size={20} /><strong>Message sent - thanks!</strong><p>We'll get back to you shortly at the email you provided.</p><button className="primary-button" onClick={() => window.location.reload()}>Send another <Send size={15} /></button></div>) : (<form className="contact-fields" onSubmit={handleSubmit}><input type="hidden" name="cf-turnstile-response" value={turnstileToken} /><input placeholder="Enter your name" name="name" required /><input placeholder="Enter your work email" type="email" name="email" required /><ValidationError prefix="Email" field="email" errors={state.errors} /><input placeholder="Enter your company" name="company" /><input placeholder="Enter your role" name="role" /><textarea placeholder="Tell us what you're investigating..." name="message" rows={3} required /><ValidationError prefix="Message" field="message" errors={state.errors} /><div className="contact-turnstile"><Turnstile siteKey="0x4AAAAAAEfHNxAH4NRkLi4K" onSuccess={setTurnstileToken} onError={() => setTurnstileToken('')} onExpire={() => setTurnstileToken('')} /></div><button className="primary-button" type="submit" disabled={state.submitting || !turnstileToken}>{state.submitting ? 'Sending...' : 'Contact Segurara'} <Send size={15} /></button></form>)}</div></section>;
}
