import { useState } from 'react';
import { useForm, ValidationError } from '@formspree/react';
import { Turnstile } from '@marsidev/react-turnstile';
import { Check, Send } from 'lucide-react';
import { SectionLabel } from '../../shared/SectionLabel';

export function AboutContact() {
  const [state, handleSubmit] = useForm('xgaeeoov');
  const [turnstileToken, setTurnstileToken] = useState('');
  return <section className="section-pad about-contact"><div className="about-block"><SectionLabel>ABOUT SEGURARA</SectionLabel><h2>Security intelligence built around <em>context.</em></h2><p>Segurara is designed to help security teams connect application, API, identity, workload, AI-service, and infrastructure activity within an evidence-supported investigation context.</p><div className="about-meta"><span>Founded <b>November 2022</b></span><span>Segurara Technologies (Pvt) Ltd<br />Segurara Technologies LLC</span><span className="about-email">Email <b>info@segurara.com</b></span></div></div><div className="contact-card" id="contact"><div><SectionLabel>GET IN TOUCH</SectionLabel><h2>Let's build better <em>security context.</em></h2></div>{state.succeeded ? (<div className="contact-success"><Check size={20} /><strong>Message sent - thanks!</strong><p>We'll get back to you shortly at the email you provided.</p><button className="primary-button" onClick={() => window.location.reload()}>Send another <Send size={15} /></button></div>) : (<form className="contact-fields" onSubmit={handleSubmit}><input type="hidden" name="cf-turnstile-response" value={turnstileToken} /><input placeholder="Enter your name" name="name" required /><input placeholder="Enter your work email" type="email" name="email" required /><ValidationError prefix="Email" field="email" errors={state.errors} /><input placeholder="Enter your company" name="company" /><input placeholder="Enter your role" name="role" /><textarea placeholder="Tell us what you're investigating..." name="message" rows={3} required /><ValidationError prefix="Message" field="message" errors={state.errors} /><div className="contact-turnstile"><Turnstile siteKey="0x4AAAAAAEfHNxAH4NRkLi4K" onSuccess={setTurnstileToken} onError={() => setTurnstileToken('')} onExpire={() => setTurnstileToken('')} /></div><button className="primary-button" type="submit" disabled={state.submitting || !turnstileToken}>{state.submitting ? 'Sending...' : 'Contact Segurara'} <Send size={15} /></button></form>)}<div className="contact-locations"><span><b>Sri Lanka</b>42 Lotus Arcade, Ward Place, Colombo 07<em>+94 11 245 7812</em></span><span><b>USA</b>425 Market Street, San Francisco, CA<em>+1 415 555 2101</em></span></div></div></section>;
}
