import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { SectionLabel } from '../../shared/SectionLabel';
import { nodeItems } from '../../shared/data';

export function GraphSection({ onProduct }: { onProduct: () => void }) {
  const [selected, setSelected] = useState(nodeItems[2]);
  const SelectedIcon = selected.icon;
  return <section id="relationships" className="section-pad graph-section"><div className="section-intro centered"><SectionLabel>SECURITY RELATIONSHIP GRAPH</SectionLabel><h2>Follow the connections behind the <em>activity.</em></h2><p>Examine how identities, applications, APIs, workloads, services, databases, and AI endpoints may be connected within an investigation.</p></div><div className="graph-panel"><div className="graph-canvas"><svg className="graph-lines" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M12 18 L32 38 L50 18 L72 38 L46 66 L80 72 M32 38 L23 78 M50 18 L46 66" /></svg>{nodeItems.map((node) => { const NodeIcon = node.icon; return <button className={`graph-node ${selected.label === node.label ? 'selected' : ''}`} style={{ left: `${node.x}%`, top: `${node.y}%`, '--node-color': node.color } as React.CSSProperties} key={node.label} onClick={() => setSelected(node)} onMouseEnter={() => setSelected(node)}><span><NodeIcon size={15} /></span><small>{node.label}</small></button>; })}<div className="graph-legend"><span><i className="legend-dot cyan" /> Application</span><span><i className="legend-dot amber" /> Identity</span><span><i className="legend-dot green" /> Workload</span></div></div><div className="entity-panel"><div className="panel-top"><span className="overline">SELECTED ENTITY</span></div><div className="entity-icon" style={{ color: selected.color }}><SelectedIcon size={22} /></div><h3>{selected.label}</h3><span className="entity-type">{selected.type}</span><div className="entity-details"><div><small>Related events</small><strong>{selected.label === 'checkout-api' ? 18 : 6}</strong></div><div><small>Risk indicators</small><strong className="rose-text">{selected.label === 'checkout-api' ? 3 : 1}</strong></div><div><small>Last activity</small><strong>14:02:24</strong></div></div><button className="ghost-button" onClick={onProduct}>Inspect entity <ArrowUpRight size={15} /></button></div></div></section>;
}
